version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["dependencies"]
    schedule:
      interval: "daily"
  - package-ecosystem: github-actions
    directory: '/'
    labels: ["dependencies"]
    schedule:
      interval: daily
