[package]
name = "mashin_primitives"
version = "0.1.0"
readme = "README.md"
description = "Primitives for mashin resources"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true