name: draft-release

on:
  push:
    tags:
      # Catches v1.2.3 and v1.2.3-rc1
      - v[0-9]+.[0-9]+.[0-9]+*
    branches:
      - lemarier-release-flow
env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: draft-release-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            draft-release-${{ runner.os }}-cargo-

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build mashin
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Zip (windows)
        if: matrix.os == 'windows-latest'
        run: cd target/release && Compress-Archive mashin.exe mashin-x86_64-pc-windows-msvc.zip

      - name: Zip (macOS)
        if: matrix.os == 'macos-latest'
        run: cd target/release && zip mashin-x86_64-apple-darwin.zip ./mashin

      - name: Zip (linux)
        if: matrix.os == 'ubuntu-latest'
        run: cd target/release && zip mashin-x86_64-unknown-linux-gnu.zip ./mashin

      - name: Draft release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          files: |
            target/release/mashin-x86_64-unknown-linux-gnu.zip
            target/release/mashin-x86_64-apple-darwin.zip
            target/release/mashin-x86_64-pc-windows-msvc.zip